<project name="Time Window Temporal Logic" default="twtl" basedir=".">
<!--
# Copyright (C) 2015-2016  Cristian Ioan Vasile <cvasile@bu.edu>
# Hybrid and Networked Systems (HyNeSs) Group, BU Robotics Lab,
# Boston University
# See license.txt file for license information.

SRC_PATH=src/
BIN_PATH=bin/
ANTLR_PATH=lib/
ANTLR= antlr-4.13.2-complete.jar
ANTLR_GEN=org.antlr.Tool
-->
    <description>
        This tools include a Time Window Temporal Logic (TWTL) parser and
        a conversion program to a Deterministic Finite State Automata (DFA).
        It can generate both exact and annotated DFAs.
        It uses the ANTLR v4 framework.
    </description>
    <!-- set global properties for this build -->
    <property name="src"   location="src" />
    <property name="bin"   location="bin" />
    <property name="lib"   location="lib" />
    <property name="dist"  location="dist" />
    <property name="antlr" location=".tools/antlr-4.13.2-complete.jar" />
    <property name="antlr4-out" location="${src}/antlr4_gen" />
    <property name="main-program" value="twtl" />
    
    <target name="init">
        <!-- Create the time stamp -->
        <tstamp>
            <format property="DSTAMP" pattern="yyyy-MM-dd-HH-mm" locale="en,US"/>
        </tstamp>
    </target>

        <target name="twtl" depends="clean"
          description="create TWTL lexer and parser" >
          <mkdir dir="${antlr4-out}"/>
          <java jar="${antlr}" fork="true" failonerror="true">
              <arg value="-Dlanguage=Python3" />
              <arg value="-visitor" />
              <arg value="-no-listener" />
              <arg value="-o" />
              <arg path="${antlr4-out}" />
              <arg path="${src}/Twtl.g4" />
          </java>
    </target>

    <target name="dist" depends="twtl,init" description="generate the distribution" >
        <!-- Create the distribution directory -->
        <mkdir dir="${dist}"/>

        <!-- Put everything in twtl-${DSTAMP}.zip archive file -->
        <zip destfile="${dist}/twtl-${DSTAMP}.zip"
             basedir="."
             excludes=".project, .pydevproject, dist/**, **/*.pyc, **/*.log"
        />
    </target>

    <target name="clean" description="clean up" >
        <delete verbose="true">
            <fileset dir="${antlr4-out}/src">
                <include name="TwtlLexer.py" />
                <include name="TwtlParser.py" />
                <include name="TwtlVisitor.py" />
                <include name="*.interp" />
                <include name="*.tokens" />
            </fileset>
        </delete>
    </target>
</project>